name: wechat_kit_extension
description: An extension package for wechat_kit.
version: 1.0.0-dev.1
homepage: https://github.com/RxReader/wechat_kit_extension

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0

dev_dependencies:
  build_runner: ^2.1.2
  flutter_lints: ^1.0.0
  json_serializable: ^5.0.0
