name: Build test

on: [ push, pull_request ]

jobs:
  test_iOS:
    name: Test iOS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze lib example/lib
      - run: cd example; flutter build ios --no-codesign

  test_android:
    name: Test android on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze lib example/lib
      - run: sudo echo "y" | sudo $ANDROID_HOME/tools/bin/sdkmanager "ndk;23.1.7779620"
      - run: cd example; flutter build apk --debug
